apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: dev
spec:
  type: NodePort
  ports:
    -
      name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: frontend